In [17]:
import numpy as np
import scipy as sp
import cvxpy as cp
import pandas as pd
import qutip as qt

np.set_printoptions(precision=4, suppress=True ,linewidth=np.inf, floatmode='fixed')

#### Example

In [6]:
# Generate a random SDP.
n = 3
p = 3
np.random.seed(1)
C = np.random.randn(n, n)
A = []
b = []
for i in range(p):
    A.append(np.random.randn(n, n))
    b.append(np.random.randn())

print(np.array(A))
print(np.array(b))

[[[-0.2494  1.4621 -2.0601]
  [-0.3224 -0.3841  1.1338]
  [-1.0999 -0.1724 -0.8779]]

 [[ 0.5828 -1.1006  1.1447]
  [ 0.9016  0.5025  0.9009]
  [-0.6837 -0.1229 -0.9358]]

 [[ 0.5304 -0.6917 -0.3968]
  [-0.6872 -0.8452 -0.6712]
  [-0.0127 -1.1173  0.2344]]]
[ 0.0422 -0.2679  1.6598]


In [7]:
# Define and solve the CVXPY problem.
# Create a symmetric matrix variable.
X = cp.Variable((n,n), symmetric=True)
# The operator >> denotes matrix inequality.
constraints = [X >> 0]
constraints += [
    cp.trace(A[i] @ X) == b[i] for i in range(p)
]
prob = cp.Problem(cp.Minimize(cp.trace(C @ X)),
                  constraints)
prob.solve()

# Print result.
print("The optimal value is", prob.value)
print("A solution X is")
print(X.value)

The optimal value is 2.6543470585557287
A solution X is
[[ 1.6081 -0.5977 -0.6958]
 [-0.5977  0.2223  0.2469]
 [-0.6958  0.2469  1.3968]]


#### Appendix (D6) Calculation Test

In [10]:
lamb = np.linspace(0,1,50)
theta = np.linspace(0,1,50)

In [26]:
cvdata = pd.read_csv('./cv.txt',header=None,delim_whitespace=True)
entdata = pd.read_csv('./entcv.txt',header=None,delim_whitespace=True)

C:\Users\128kbps\AppData\Local\Temp\ipykernel_395924\3444214984.py:1: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  cvdata = pd.read_csv('./cv.txt',header=None,delim_whitespace=True)
C:\Users\128kbps\AppData\Local\Temp\ipykernel_395924\3444214984.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  entdata = pd.read_csv('./entcv.txt',header=None,delim_whitespace=True)


In [27]:
Ham_A = np.array([[0,0],[0,1]])

In [29]:
for i in range(5):
    for j in range(5):
        X = cp.Variable((2,2), PSD=True)
        # The operator >> denotes matrix inequality.
        constraints = [
            cp.von_neumann_entr(X) >= entdata [i][j]        
        ]
        prob = cp.Problem(cp.Minimize(cp.trace(Ham_A @ X)-cvdata[i][j]),
                        constraints)
        prob.solve()

        # Print result.
        print("The optimal value is", prob.value)
        print("A solution X is")
        print(X.value)

The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solution X is
None
The optimal value is inf
A solutio