In [8]:
import numpy as np
import matplotlib.pyplot as plt

In [9]:
def function(x):
    return x
def gunction(x):
    return x


In [36]:
def N_Testing(z,i,j):
    A = [[0 for n in range(z)] for m in range(z)]

    for n in range(z):
        for m in range(z):
            try:
                if n==m:
                    A[n][m+1] = function(i)*gunction(j)
                    A[n+1][m] = function(i)*gunction(j)
            except:
                None

    return np.array(A)

In [38]:
N_Testing(3,2,3)

array([[0, 6, 0],
       [6, 0, 6],
       [0, 6, 0]])

In [41]:
1%3

1

In [44]:
asdfasdf = np.array([[1,2,3],[4,5,6],[7,8,9]])
asdf = np.linalg.eig(asdfasdf)

In [45]:
asdf

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))