In [14]:
import Hamiltonian as H
import numpy as np
import scipy as sp

In [15]:
tau = np.linspace(1,10,10)
const_tau = tau[0]

In [16]:
prop_ite_0 = np.identity(3)
loc = H.Hamiltonian_Matrix(1,3,1,0)
expp = sp.linalg.expm(loc)


In [17]:
asdf = H.Hamiltonian_Matrix(1,6,1,0)[:3,3:6]

In [18]:
sigma = 0.5 * np.matmul(np.matmul(asdf,expp),asdf) * 0.1

In [19]:
round_propagator_ite_1 = []

for i in range(10):
    round_propagator_ite_1.append(np.array((-loc-tau[i]*sigma)))

In [20]:
round_propagator_ite_1

[array([[ 0.25400013, -0.        , -0.03856942],
        [-0.        , -0.97062342, -0.        ],
        [-0.03856942, -0.        , -1.37930455]]),
 array([[ 0.14197485, -0.        , -0.07713884],
        [-0.        , -1.02238567, -0.        ],
        [-0.07713884, -0.        , -1.3925837 ]]),
 array([[ 0.02994957, -0.        , -0.11570827],
        [-0.        , -1.07414792, -0.        ],
        [-0.11570827, -0.        , -1.40586285]]),
 array([[-0.0820757 , -0.        , -0.15427769],
        [-0.        , -1.12591018, -0.        ],
        [-0.15427769, -0.        , -1.419142  ]]),
 array([[-0.19410098, -0.        , -0.19284711],
        [-0.        , -1.17767243, -0.        ],
        [-0.19284711, -0.        , -1.43242115]]),
 array([[-0.30612626, -0.        , -0.23141653],
        [-0.        , -1.22943468, -0.        ],
        [-0.23141653, -0.        , -1.4457003 ]]),
 array([[-0.41815153, -0.        , -0.26998596],
        [-0.        , -1.28119693, -0.        ],
        

In [21]:
A = []
for i in range(len(tau)):
    A.append(np.array(prop_ite_0 + round_propagator_ite_1)*tau[i])

In [22]:
A

[array([[[ 1.25400013,  0.        , -0.03856942],
         [ 0.        ,  0.02937658,  0.        ],
         [-0.03856942,  0.        , -0.37930455]],
 
        [[ 1.14197485,  0.        , -0.07713884],
         [ 0.        , -0.02238567,  0.        ],
         [-0.07713884,  0.        , -0.3925837 ]],
 
        [[ 1.02994957,  0.        , -0.11570827],
         [ 0.        , -0.07414792,  0.        ],
         [-0.11570827,  0.        , -0.40586285]],
 
        [[ 0.9179243 ,  0.        , -0.15427769],
         [ 0.        , -0.12591018,  0.        ],
         [-0.15427769,  0.        , -0.419142  ]],
 
        [[ 0.80589902,  0.        , -0.19284711],
         [ 0.        , -0.17767243,  0.        ],
         [-0.19284711,  0.        , -0.43242115]],
 
        [[ 0.69387374,  0.        , -0.23141653],
         [ 0.        , -0.22943468,  0.        ],
         [-0.23141653,  0.        , -0.4457003 ]],
 
        [[ 0.58184847,  0.        , -0.26998596],
         [ 0.        , -0.281196

In [23]:
class Calculator:
    def __init__(self):
        self.result = 0
    
    def add(self, num):
        self.result += num
        return self.result

cal1 = Calculator()
cal2 = Calculator()

print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10


In [24]:
A = [0,0,0,0,0,0,0]
C = [1,2,3,4,5,6,7]

for i in range(len(A)):
    B = np.ones((3,3))

    B[0,0] = C[i]
    B[1,1] = C[i]
    B[2,2] = C[i]

    A[i] = B

print(np.array(A))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[2. 1. 1.]
  [1. 2. 1.]
  [1. 1. 2.]]

 [[3. 1. 1.]
  [1. 3. 1.]
  [1. 1. 3.]]

 [[4. 1. 1.]
  [1. 4. 1.]
  [1. 1. 4.]]

 [[5. 1. 1.]
  [1. 5. 1.]
  [1. 1. 5.]]

 [[6. 1. 1.]
  [1. 6. 1.]
  [1. 1. 6.]]

 [[7. 1. 1.]
  [1. 7. 1.]
  [1. 1. 7.]]]


In [25]:
a = np.linspace(1,10)
b = np.ones((3,3))

In [26]:
a*b

ValueError: operands could not be broadcast together with shapes (50,) (3,3) 

In [47]:
A =[np.identity(3) for i in range(10)]
arr = np.array(A)
norm = np.linalg.norm(arr)

In [50]:
arr/norm

array([[[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419, 0.        , 0.        ],
        [0.        , 0.18257419, 0.        ],
        [0.        , 0.        , 0.18257419]],

       [[0.18257419,

In [49]:
norm

5.477225575051661