In [2]:
import numpy as np
import scipy as sp
import Hamiltonian as H

In [3]:
tau = np.linspace(0,1,10)
k = np.linspace(1,10,10)
g = 0.2

In [4]:
initial = np.identity(3)

def H_loc():
    HE0 = H.Standard_even_Eigenval(1,3,0)
    HE1 = H.Standard_even_Eigenval(1,3,1)
    HO = H.Standard_odd_Eigenval(1,3,0)

    A = np.array([[HE0,0,0],[0,HO,0],[0,0,HE1]])

    return A

def H_exp(tau):
    i = 0
    blank = []
    HE1 = np.exp(H.Standard_even_Eigenval(1,3,0))
    HE2 =np.exp(H.Standard_even_Eigenval(1,3,1))
    HO = np.exp(H.Standard_odd_Eigenval(1,3,0))
    for k in range(len(tau)):
        mat = np.array([[tau[k],0,0],[0,tau[k],0],[0,0,tau[k]]])
        matrix = np.array([[HE1,0,0],[0,HO,0],[0,0,HE2]])
        blank.append(mat @ matrix)#sp.linalg.expm(matrix))

    return np.array(blank)

def N(a):
    HE1 = H.Standard_even_Eigenvec(1,3,0)
    HE2 = H.Standard_even_Eigenvec(1,3,1)
    HO = H.Standard_odd_Eigenvec(1,3,0)

    matrix = [[0,0,0],[0,0,0],[0,0,0]]

    matrix[0][1] = matrix [1][0] = g * np.matmul(HO,HE1)
    matrix[1][2] = matrix [2][1] = g * np.matmul(HE2,HO)

    return matrix



def sigma(H_loc,N,tau,n):
    N_arr = []
    for i in range(n):
        N_arr.append(N(1))
        
    sigma_cut = []
    V_cut = 0
    i = 0 
    Nmatrx = N
    while i != n :
        V_cut = H.interact(tau,0.2,0.2,10)[i]
        sigma_cut.append(V_cut * 0.5 * (N_arr[i] @ H_loc[i] @ N_arr[i]))
        i = i + 1
    return sigma_cut

def propagator(H_loc, tau):
    #blank array
    roundprop = np.zeros(10)
    roundprop_array = np.zeros(len(roundprop)+1)

    prop = np.zeros(10)
    prop_array = np.zeros(len(prop)+1)

    #initial condition
    roundprop[0] = - H_loc[0]*initial - tau[0]*np.matmul(sigma(H_loc(tau),N,tau,0),initial)
    prop[0] = initial

    #update propagator condition
    for i in range(len(prop)):
        prop_array[i] = prop[i-1] + roundprop[j]*tau[0]
        prop[i+1] = prop_array[i]

    #update differentiable condition
    for i in range(len(roundprop)):
        #blank variable for summation
        b = 0
        for j in range(i):
            b = b + prop[j]
        roundprop_array[i] = -H_loc(tau)[i]*prop[i]-tau[0]*b*sigma(H_loc(tau),N,tau,i)
        roundprop[i+1] = roundprop_array[i]

    return prop

In [5]:
sigma(H_exp(tau),N,tau,10)


[array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[ 0.00104302,  0.        , -0.00035896],
        [ 0.        ,  0.00046518,  0.        ],
        [-0.00035896,  0.        ,  0.00012354]]),
 array([[ 0.00110279,  0.        , -0.00037954],
        [ 0.        ,  0.00049184,  0.        ],
        [-0.00037954,  0.        ,  0.00013062]]),
 array([[ 0.00096257,  0.        , -0.00033128],
        [ 0.        ,  0.0004293 ,  0.        ],
        [-0.00033128,  0.        ,  0.00011401]]),
 array([[ 8.21783596e-04,  0.00000000e+00, -2.82824931e-04],
        [ 0.00000000e+00,  3.66512769e-04,  0.00000000e+00],
        [-2.82824931e-04,  0.00000000e+00,  9.73369897e-05]]),
 array([[ 7.20255865e-04,  0.00000000e+00, -2.47883160e-04],
        [ 0.00000000e+00,  3.21231736e-04,  0.00000000e+00],
        [-2.47883160e-04,  0.00000000e+00,  8.53114348e-05]]),
 array([[ 6.59571888e-04,  0.00000000e+00, -2.26998171e-04],
        [ 0.00000000e+00,  2.94166883e-04,  0.00000000

In [6]:
H.Standard_odd_Eigenval(1,3,1)

4.032127023771304

In [7]:
H.coupling(0.2,0.2,10)

array([0.08942484, 0.12639003, 0.15464123, 0.17831574, 0.19900744, 0.21752842, 0.23435763, 0.24980492, 0.2640841 , 0.2773501 ])

In [8]:
H.interact(tau,0.2,0.2,10)

array([0.43383755, 0.20963657, 0.11082537, 0.06448932, 0.04129267, 0.02895291, 0.02209461, 0.01826113, 0.01630022, 0.01569591])

In [9]:
NCA = np.array([[5.3302,0,0.00201489],[0,0.000235822,0],[0.00201489,0,-9.0148e-07]])

In [18]:
expp = np.exp(-1.67343)

In [15]:
check = NCA*expp

In [16]:
check

array([[ 2.84122037e+01,  0.00000000e+00,  1.07402096e-02],
       [ 0.00000000e+00,  1.25703026e-03,  0.00000000e+00],
       [ 1.07402096e-02,  0.00000000e+00, -4.80526686e-06]])

In [17]:
check @ check

array([[8.07253435e+02, 0.00000000e+00, 3.05152971e-01],
       [0.00000000e+00, 1.58012508e-06, 0.00000000e+00],
       [3.05152971e-01, 0.00000000e+00, 1.15352125e-04]])

In [19]:
5.33043 * expp

1.0000019103476299

In [32]:
def aRecursive(n):
    print(n)
    if n == 1:
        return 3
    else:
        #print(2 * aRecursive(n-1) + 5)
        return 2 * aRecursive(n-1) + 5

In [33]:
aRecursive(3) 

3
2
1


27

In [76]:
array0 = np.array([[2,2,2],[2,2,2],[2,2,2]])
array1 = np.array([array0 for i in range(10)])

def test1(a):
    arr0 = np.array([[2,2,2],[2,2,2],[2,2,2]])

    arr1 = np.array([arr0 for i in range(10)])
    arr1[0] = np.identity(3)
    
    for i in range(1,10,1):
        arr1[i] = arr1[i-1] + a[i-1]
    
    return arr1

def test2(a):
    arr0 = [0,0,0,0,0,0,0,0,0,0]
    for i in range(10):
        arr0[i] = a[i] + np.identity(3)
    
    return arr0

def test3():
    arr1 = np.full(10,1)
    arr2 = [[[1,1,1],[1,1,1],[1,1,1]] for i in range(10)]

    for j in range(10):
        if j == 0:
            arr1 = test2(array1)
            arr2 = test1(arr1)
        else:
            arr1 = test2(arr2)
            arr2 = test1(arr1)
            print(arr1,'\n')

    return arr1




In [77]:
test3()

[array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]]), array([[5., 2., 2.],
       [2., 5., 2.],
       [2., 2., 5.]]), array([[8., 4., 4.],
       [4., 8., 4.],
       [4., 4., 8.]]), array([[11.,  6.,  6.],
       [ 6., 11.,  6.],
       [ 6.,  6., 11.]]), array([[14.,  8.,  8.],
       [ 8., 14.,  8.],
       [ 8.,  8., 14.]]), array([[17., 10., 10.],
       [10., 17., 10.],
       [10., 10., 17.]]), array([[20., 12., 12.],
       [12., 20., 12.],
       [12., 12., 20.]]), array([[23., 14., 14.],
       [14., 23., 14.],
       [14., 14., 23.]]), array([[26., 16., 16.],
       [16., 26., 16.],
       [16., 16., 26.]]), array([[29., 18., 18.],
       [18., 29., 18.],
       [18., 18., 29.]])] 

[array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]]), array([[4., 0., 0.],
       [0., 4., 0.],
       [0., 0., 4.]]), array([[9., 2., 2.],
       [2., 9., 2.],
       [2., 2., 9.]]), array([[17.,  6.,  6.],
       [ 6., 17.,  6.],
       [ 6.,  6., 17.]]), array([[28., 1

[array([[2., 0., 0.],
        [0., 2., 0.],
        [0., 0., 2.]]),
 array([[4., 0., 0.],
        [0., 4., 0.],
        [0., 0., 4.]]),
 array([[8., 0., 0.],
        [0., 8., 0.],
        [0., 0., 8.]]),
 array([[16.,  0.,  0.],
        [ 0., 16.,  0.],
        [ 0.,  0., 16.]]),
 array([[32.,  0.,  0.],
        [ 0., 32.,  0.],
        [ 0.,  0., 32.]]),
 array([[64.,  0.,  0.],
        [ 0., 64.,  0.],
        [ 0.,  0., 64.]]),
 array([[128.,   0.,   0.],
        [  0., 128.,   0.],
        [  0.,   0., 128.]]),
 array([[256.,   0.,   0.],
        [  0., 256.,   0.],
        [  0.,   0., 256.]]),
 array([[512.,   0.,   0.],
        [  0., 512.,   0.],
        [  0.,   0., 512.]]),
 array([[1025.,    2.,    2.],
        [   2., 1025.,    2.],
        [   2.,    2., 1025.]])]

In [80]:
a = 0
b = 0

for i in range(10):
    a = b + 1
    b = a
    print(b)

1
2
3
4
5
6
7
8
9
10
