In [3]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random

import pandas as pd

In [4]:
def value(n):
    array=np.random.rand(n)

    for i in range(0,n,1):
        a=array[i]*10
        b=math.floor(a)

        array[i]=b
    
    return array

In [5]:
value(4)

array([5., 7., 5., 0.])

In [9]:
def prob_array(n):
    value_s=value(n)
    events=np.sum(value_s)

    prob_array=value_s/events
    
    return prob_array

In [29]:
def symmetric2(n):    
    x=prob_array(n)
    standard_array=np.zeros((n,n))
    a=np.random.permutation(x)


    for i in range(n):
        standard_array[i]=a
        
    #print(standard_array) 

    for j in range(n):
        standard_array[j:n,i]=standard_array[j,j:n]
        print(standard_array[1][j])
    
    for k in range(n):
        standard_array[k][k]=standard_array[1][k]
    
    print(standard_array)

    transpose_array=standard_array.T
    #print(transpose_array)

    symmetric_array=(transpose_array+standard_array)/2
    #print(symmetric_array)

    return symmetric_array

In [31]:
symmetric2(4)

0.36363636363636365
0.0
0.2727272727272727
0.0
[[0.36363636 0.         0.27272727 0.36363636]
 [0.36363636 0.         0.27272727 0.        ]
 [0.36363636 0.         0.27272727 0.27272727]
 [0.36363636 0.         0.27272727 0.        ]]


array([[0.36363636, 0.18181818, 0.31818182, 0.36363636],
       [0.18181818, 0.        , 0.13636364, 0.        ],
       [0.31818182, 0.13636364, 0.27272727, 0.27272727],
       [0.36363636, 0.        , 0.27272727, 0.        ]])

In [ ]:
def symmetric(n):    
    x=prob_array(n)
    standard_array=np.zeros((n,n))

#t=np.random.permutation(x)
#print(t)


    for i in range(n):
        a=np.random.permutation(x)
        summation=np.sum(a)
        standard_array[i]=a

    transpose_array=standard_array.T
    print(transpose_array)

    symmetric_array=(transpose_array+standard_array)/2
    print(symmetric_array)

    return symmetric_array


In [ ]:
symmetric(5)

[[0.22222222 0.33333333 0.05555556 0.22222222 0.05555556]
 [0.38888889 0.38888889 0.33333333 0.         0.38888889]
 [0.05555556 0.05555556 0.22222222 0.05555556 0.        ]
 [0.33333333 0.         0.38888889 0.38888889 0.33333333]
 [0.         0.22222222 0.         0.33333333 0.22222222]]
[[0.22222222 0.36111111 0.05555556 0.27777778 0.02777778]
 [0.36111111 0.38888889 0.19444444 0.         0.30555556]
 [0.05555556 0.19444444 0.22222222 0.22222222 0.        ]
 [0.27777778 0.         0.22222222 0.38888889 0.33333333]
 [0.02777778 0.30555556 0.         0.33333333 0.22222222]]


array([[0.22222222, 0.36111111, 0.05555556, 0.27777778, 0.02777778],
       [0.36111111, 0.38888889, 0.19444444, 0.        , 0.30555556],
       [0.05555556, 0.19444444, 0.22222222, 0.22222222, 0.        ],
       [0.27777778, 0.        , 0.22222222, 0.38888889, 0.33333333],
       [0.02777778, 0.30555556, 0.        , 0.33333333, 0.22222222]])

In [ ]:
transpose_array=standard_array.T
#print(transpose_array)

symmetric_array=(transpose_array+standard_array)/2
print(symmetric_array)

[[0.04166667 0.04166667 0.20833333 0.33333333 0.125     ]
 [0.04166667 0.375      0.1875     0.04166667 0.125     ]
 [0.20833333 0.1875     0.33333333 0.29166667 0.35416667]
 [0.33333333 0.04166667 0.29166667 0.20833333 0.125     ]
 [0.125      0.125      0.35416667 0.125      0.375     ]]


In [17]:
def matmul(n):
    fundamental_postulate=symmetric2(n)
    print(fundamental_postulate)

    for i in range(n):
        fundamental_postulate=fundamental_postulate*fundamental_postulate
        print(fundamental_postulate)
    
    return fundamental_postulate

In [18]:
matmul(4)

[[0.         0.15384615 0.38461538 0.        ]
 [0.         0.15384615 0.38461538 0.15384615]
 [0.         0.15384615 0.38461538 0.38461538]
 [0.         0.15384615 0.38461538 0.38461538]]
[[0.         0.07692308 0.19230769 0.        ]
 [0.07692308 0.15384615 0.26923077 0.15384615]
 [0.19230769 0.26923077 0.38461538 0.38461538]
 [0.         0.15384615 0.38461538 0.38461538]]
[[0.         0.00591716 0.03698225 0.        ]
 [0.00591716 0.02366864 0.07248521 0.02366864]
 [0.03698225 0.07248521 0.14792899 0.14792899]
 [0.         0.02366864 0.14792899 0.14792899]]
[[0.00000000e+00 3.50127797e-05 1.36768671e-03 0.00000000e+00]
 [3.50127797e-05 5.60204475e-04 5.25410525e-03 5.60204475e-04]
 [1.36768671e-03 5.25410525e-03 2.18829873e-02 2.18829873e-02]
 [0.00000000e+00 5.60204475e-04 2.18829873e-02 2.18829873e-02]]
[[0.00000000e+00 1.22589474e-09 1.87056692e-06 0.00000000e+00]
 [1.22589474e-09 3.13829053e-07 2.76056220e-05 3.13829053e-07]
 [1.87056692e-06 2.76056220e-05 4.78865133e-04 4.78865

array([[0.00000000e+00, 1.50281791e-18, 3.49902062e-12, 0.00000000e+00],
       [1.50281791e-18, 9.84886748e-14, 7.62070364e-10, 9.84886748e-14],
       [3.49902062e-12, 7.62070364e-10, 2.29311815e-07, 2.29311815e-07],
       [0.00000000e+00, 9.84886748e-14, 2.29311815e-07, 2.29311815e-07]])

In [ ]:
prob_matrix=np.identity(5)
pa=prob_array(5)

for i in range(5):
    for j in range(5):
        prob_matrix[i][j]=pa[i]*prob_matrix[i][j]

prob_matrix

array([[0.125     , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.04166667, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.375     , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.20833333]])

In [ ]:
prob_matrix=np.identity(5)

for i in range(5):
    for j in range(5):
        prob_matrix[i][j]=pa[i]*prob_matrix[i][j]

        if prob_matrix[i][j]==0:
            if i==0:
                prob_matrix[i][j]=pa[j]
            if j==0:
                prob_matrix[i][j]=pa[i]
        


prob_matrix


array([[0.125     , 0.04166667, 0.375     , 0.25      , 0.20833333],
       [0.04166667, 0.04166667, 0.        , 0.        , 0.        ],
       [0.375     , 0.        , 0.375     , 0.        , 0.        ],
       [0.25      , 0.        , 0.        , 0.25      , 0.        ],
       [0.20833333, 0.        , 0.        , 0.        , 0.20833333]])

In [ ]:
part1=prob_matrix[1][2:5]
part1

array([0., 0., 0.])

In [ ]:
value_2=prob_array(3)
value_2

array([0.64285714, 0.        , 0.35714286])