In [1]:
import numpy as np

In [2]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
a=np.arange(12).reshape((3,4))

In [5]:
a.shape

(3, 4)

In [8]:
print(a.ndim)
print(a.size)

2
12


In [12]:
a.T
b=a.reshape((2,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [13]:
a[:2,:]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [14]:
a[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [18]:
M=np.array([(10,20),(30,40),(50,60)])
M
M.size
M.dtype

dtype('int32')