In [1]:
import numpy as np

In [3]:
import numpy as np

# 4개의 (2,2) 행렬 생성
A = np.array([[1, 2], 
              [3, 4]])

B = np.array([[5, 6], 
              [7, 8]])

C = np.array([[9, 10], 
              [11, 12]])

D = np.array([[13, 14], 
              [15, 16]])

# 4개의 행렬을 2x2 블록 행렬로 결합
# 결과는 4x4 행렬이 됩니다
# [[A, B],
#  [C, D]]
result = np.block([[A, B], 
                   [C, D]])

print("행렬 A:")
print(A)
print("\n행렬 B:")
print(B)
print("\n행렬 C:")
print(C)
print("\n행렬 D:")
print(D)
print("\n블록 행렬 결과:")
print(result)

# 결과 행렬의 크기 확인
print("\n결과 행렬의 shape:", result.shape)

행렬 A:
[[1 2]
 [3 4]]

행렬 B:
[[5 6]
 [7 8]]

행렬 C:
[[ 9 10]
 [11 12]]

행렬 D:
[[13 14]
 [15 16]]

블록 행렬 결과:
[[ 1  2  5  6]
 [ 3  4  7  8]
 [ 9 10 13 14]
 [11 12 15 16]]

결과 행렬의 shape: (4, 4)
